services:
  client:
    image: client:v1.0.2
    build:
      context: ./client
      args:
        API_URL: http://localhost:8086/api-salute
    container_name: exu2-cliente
    ports:
      - "5173:80"
    networks:
      - exu2-ayad-net

  operations:
    image: operations:v1.0.2
    build:
      context: ./server
    container_name: exu2-operaciones
    environment:
      SERVER_PORT: 8080
    ports:
      - "8086:8080"
    networks:
      - exu2-ayad-net

networks:
  exu2-ayad-net:
    external: true